name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
  push:
    branches:
      - main
    
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn lint

      - name: Run Build
        run: yarn build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist

  # security_audit:
  #   name: Security Audit
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version-file: ".nvmrc"
  #         cache: "yarn"

  #     - name: Install Dependencies
  #       run: yarn install --frozen-lockfile

  #     - name: Run Security Audit
  #       run: yarn audit --groups dependencies

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Comment or remove this line to enable tests by default
    if: github.event_name == 'workflow_dispatch'
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test
        env:
          TEST_USER_SECRET_KEY: "[243,209,26,170,233,220,87,246,186,249,184,131,192,150,226,199,18,71,26,246,200,191,25,134,244,44,8,42,32,11,185,194,110,166,26,137,37,31,69,91,254,102,98,209,147,249,231,211,203,50,49,57,51,108,131,241,247,65,131,158,141,92,105,228]"
          RPC_API_CLUSTER: https://rpc.ankr.com/solana_devnet
          WSS_API_CLUSTER: wss://api.devnet.solana.com/
          USER_ID: 8SvkUtJZCyJwSQGkiszwcRcPv7c8pPSr8GVEppGNN7DV
          HELIUS_API_URL: https://mainnet.helius-rpc.com/?api-key=89bb46d5-c874-4de8-873c-4a7cebdd7376

  publish:
    name: Publish
    runs-on:
      ubuntu-latest
      # Add `test` here if we are good. add back security_audit after meteora dependencies are fixed
    needs: [build,]
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./dist # Adjust this path to where you want to place the build files

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Configure NPM to use private registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish
        run: yarn publish --access restricted
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
